### ISSUE TITLE
Disable "remove" and "restore" buttons when backing up?

### ISSUE THREAD

**Issue by cassidyjames** [chasinglogic/tardis#23]
I'm not 100% how this works, but it might make sense to make the remove and restore buttons on drives insensitive while backing up. I don't think it makes sense to try to restore while in the middle of backing up, and I'm not sure what would happen if you remove a drive in the middle of backing up.

**Comment by chasinglogic** [comment]
Because rsync is very robust removing a drive during backup is only as dangerous as unplugging a drive without safely removing it via the eject button.

rsync will happily pick back up where it left off on a drive that's unplugged midstream.

I will disable the buttons while a backup is in progress.
