### ISSUE TITLE
Enable cloud backups

### ISSUE THREAD

**Issue by 20alice2emanueli** [chasinglogic/tardis#31]
Hello, I would like to give you an idea for this wonderful application! You could put the option to log into the google drive account and the One Drive account and make the backups directly on the cloud! That would be great, and the app icon could be in the System Settings App instead of the app menu. Thank you! I am very happy for the new apps, this makes Elementary OS even better.

**Comment by chasinglogic** [comment]
Since we use GLib to see available volumes we can already see cloud drives that are mounted via gvfs. Elementary OS does not support this currently but if you use another gnome based distribution like Ubuntu Tardis will happily backup to cloud drives.

I do not know (and cannot find any issues) if elementary OS will ever support cloud drives this way and hacking it in via this application seems very difficult and outside the scope of Tardis.

Since this already works when the OS supports cloud drives I'm going to close this as Won't Fix
